<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Monitorian.Core</RootNamespace>
    <AssemblyName>Monitorian.Core</AssemblyName>
    <TargetPlatformVersion>10.0</TargetPlatformVersion>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.19041.1" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ScreenFrame\ScreenFrame.csproj" />
    <ProjectReference Include="..\StartupAgency\StartupAgency.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Management" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.Configuration" />
  </ItemGroup>
</Project>